DROP SEQUENCE Member_m_no_SEQ;

CREATE SEQUENCE Member_m_no_SEQ NOMAXVALUE NOCACHE NOORDER NOCYCLE;

DROP SEQUENCE Jumun_j_no_SEQ;

CREATE SEQUENCE Jumun_j_no_SEQ NOMAXVALUE NOCACHE NOORDER NOCYCLE;

DROP SEQUENCE jd_jd_no_SEQ;

CREATE SEQUENCE jd_jd_no_SEQ NOMAXVALUE NOCACHE NOORDER NOCYCLE;

DROP SEQUENCE Item_i_no_SEQ;

CREATE SEQUENCE Item_i_no_SEQ NOMAXVALUE NOCACHE NOORDER NOCYCLE;

DROP SEQUENCE SEAT_s_no_SEQ;

CREATE SEQUENCE SEAT_s_no_SEQ NOMAXVALUE NOCACHE NOORDER NOCYCLE;

DROP SEQUENCE Reserve_r_no_SEQ;

CREATE SEQUENCE Reserve_r_no_SEQ NOMAXVALUE NOCACHE NOORDER NOCYCLE;

DROP SEQUENCE board_b_no_SEQ;

CREATE SEQUENCE board_b_no_SEQ NOMAXVALUE NOCACHE NOORDER NOCYCLE;
